# Generated by Django 6.1.1 on 2026-10-07 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='CartWave', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/logo/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/favicon/')),
                ('site_name', models.CharField(default='CartWave', max_length=100, verbose_name='Site Name')),
            ],
            options={
                'verbose_name': 'site configuration',
                'verbose_name_plural': 'site configurations',
            },
        ),
    ]
