# Generated by Django 6.1.1 on 2026-10-03 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='site_name',
            field=models.CharField(default='CartWave', max_length=100, verbose_name='Site Name'),
        ),
    ]
