# Generated by Django 6.1.1 on 2026-10-03 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_siteconfig_site_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteconfig',
            old_name='desscription',
            new_name='description',
        ),
    ]
