# Generated by Django 6.1.1 on 2026-09-29 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_features',
            new_name='is_featured',
        ),
    ]
